package main

import (
	"encoding/json"
	"fmt"
	"log"
	"math/rand"
	"net/http"
	"strconv"
	"time"

	"github.com/gorilla/mux"

	_ "github.com/swaggo/http-swagger/example/gorilla/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
	_ "github.com/swaggo/swag"
)

// Alarm represents an alarm object.
type Alarm struct {
	ID        int       `json:"id"`
	Title     string    `json:"title"`
	Message   string    `json:"message"`
	StartTime time.Time `json:"startTime"`
	Severity  string    `json:"severity"`
}

var alarms []Alarm

// @title Alarm API
// @version 1.0
// @description This is a sample API for managing alarms.
// @termsOfService https://example.com/terms-of-service
// @contact.name API Support
// @contact.url https://www.example.com/support
// @license.name Apache 2.0
// @license.url https://www.apache.org/licenses/LICENSE-2.0.html
// @BasePath /api/v1
// @host localhost:8080

// @Summary Generate Alarm
// @Description Generate a new alarm
// @Tags Alarms
// @Accept json
// @Produce json
// @Param alarm body Alarm true "Alarm object that needs to be generated"
// @Success 201 {object} Alarm
// @Router /generateAlarms [post]
func createAlarm(w http.ResponseWriter, r *http.Request) {
	var newAlarm Alarm
	_ = json.NewDecoder(r.Body).Decode(&newAlarm)

	newAlarm.ID = rand.Intn(9999)
	newAlarm.StartTime = time.Now()

	alarms = append(alarms, newAlarm)
	w.WriteHeader(http.StatusCreated)
	json.NewEncoder(w).Encode(newAlarm)
	fmt.Fprintf(w, "Alarm with ID %d and title %s is generated\n", newAlarm.ID, newAlarm.Title)
}

// @Summary Get all Alarms
// @Description Get all alarms
// @Tags Alarms
// @Accept json
// @Produce json
// @Success 200 {array} Alarm
// @Router /alarms [get]
func getAllAlarms(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(alarms)
}

// @Summary Clear Alarm
// @Description Clear an alarm by ID
// @Tags Alarms
// @Accept json
// @Produce json
// @Param id path int true "Alarm ID to clear"
// @Success 200 {string} string "Alarm cleared successfully"
// @Failure 404 {string} string "Alarm not found"
// @Router /clearAlarms/{id} [delete]
func deleteAlarm(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id, _ := strconv.Atoi(params["id"])

	for index, alarm := range alarms {
		if alarm.ID == id {
			alarms = append(
				alarms[:index], alarms[index+1:]...)
			fmt.Fprintf(w, "Alarm with title %s and ID %d has been deleted\n", alarm.Title, alarm.ID)
			break
		}
		w.WriteHeader(http.StatusOK)
	}
	w.WriteHeader(http.StatusNotFound)
}

// @Summary Update Alarm
// @Description Update an alarm by ID
// @Tags Alarms
// @Accept json
// @Produce json
// @Param id path int true "Alarm ID to update"
// @Param alarm body Alarm true "Updated Alarm object"
// @Success 200 {object} Alarm
// @Failure 404 {string} string "Alarm not found"
// @Router /updateAlarms/{id} [put]
func updateAlarm(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	id, _ := strconv.Atoi(params["id"])

	var updateAlarm Alarm
	_ = json.NewDecoder(r.Body).Decode(&updateAlarm)

	for index, alarm := range alarms {
		if alarm.ID == id {
			alarm.Title = updateAlarm.Title
			alarm.Message = updateAlarm.Message
			alarm.Severity = updateAlarm.Severity

			alarms[index] = alarm
			json.NewEncoder(w).Encode(alarm)
			fmt.Fprintf(w, "Alarm with title %s is updated\n", alarm.Title)
			return
		}
	}
	w.WriteHeader(http.StatusNotFound)
	fmt.Fprintf(w, "Alarm with ID %d is not found", id)
}

func handleRequests() {
	router := mux.NewRouter().StrictSlash(true)

	router.HandleFunc("/generateAlarms", createAlarm).Methods("POST")
	router.HandleFunc("/alarms", getAllAlarms).Methods("GET")
	router.HandleFunc("/clearAlarms/{id}", deleteAlarm).Methods("DELETE")
	router.HandleFunc("/updateAlarms/{id}", updateAlarm).Methods("PUT")

	// Swagger UI
	/*router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("/docs/swagger.json"), // The url pointing to API definition"
	))*/

	/*router.PathPrefix("/swagger/").Handler(http.StripPrefix("/swagger/", http.FileServer(http.Dir("./docs/swagger-ui"))))

	router.HandleFunc("/swagger/doc.json", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./docs/swagger.json")
	})*/

	router.PathPrefix("/swagger/").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), //The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)
	log.Println("Starting API Gateway on :8080")
	log.Fatal(http.ListenAndServe(":8080", router))
}

func main() {
	// Seed random number generator
	rand.Seed(time.Now().UnixNano())

	// Initialize some sample alarms
	alarms = append(alarms, Alarm{ID: rand.Intn(9999), Message: "Write the test cases for the sample code", Title: "Testing", StartTime: time.Now(), Severity: "Major"})
	alarms = append(alarms, Alarm{ID: rand.Intn(9999), Title: "Testing", Message: "Testing successfully completed", StartTime: time.Now(), Severity: "Minor"})
	alarms = append(alarms, Alarm{ID: rand.Intn(9999), Title: "Execution", Message: "Execute the above code", StartTime: time.Now(), Severity: "Major"})

	http.Handle("/swagger/", http.StripPrefix("/swagger/", http.FileServer(http.Dir("./docs"))))
	http.HandleFunc("/swagger/doc.json", func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r, "./docs/swagger.json")
	})

	handleRequests()
}
